version: '3.8'

services:
  XFoodi-frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: XFoodi-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - INTERNAL_ADMIN_API_URL=https://admin.xfoodi.com/api
      - INTERNAL_API_URL=https://demo.xfoodi.com/api
      - NEXT_PUBLIC_API_URL=https://demo.xfoodi.com/api
      - NEXT_PUBLIC_ADMIN_API_URL=https://admin.xfoodi.com/api
    restart: unless-stopped
    networks:
      - XFoodi-network

networks:
  XFoodi-network:
    driver: bridge
