export const API_ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    GOOGLE: '/auth/google',
    REGISTER: '/auth/register',
    CHECK_PHONE: '/auth/customer/check-phone',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    CHANGE_PASSWORD: '/auth/change-password',
    RESET_PASSWORD: '/auth/reset-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    CONFIRM_EMAIL: '/auth/confirm-email',
    RESEND_CONFIRMATION_EMAIL: '/auth/resend-confirmation-email',
    REFRESH_TOKEN: '/auth/refresh-token',
    TWO_FACTOR_SETUP: '/auth/2fa/setup',
    TWO_FACTOR_ENABLE: '/auth/2fa/enable',
    TWO_FACTOR_DISABLE: '/auth/2fa/disable',
    TWO_FACTOR_STATUS: '/auth/2fa/status',
    TWO_FACTOR_VALIDATE: '/auth/2fa/validate',
    TWO_FACTOR_REGENERATE_BACKUP_CODES: '/auth/2fa/regenerate-backup-codes',
    TWO_FACTOR_SETUP_NEW_DEVICE: '/auth/2fa/setup-new-device',
    TWO_FACTOR_CONFIRM_NEW_DEVICE: '/auth/2fa/confirm-new-device',
  },
  USERS: {
    ME: '/users/me',
    CHANGE_PASSWORD: '/users/change-password',
  },
  RESTAURANT_APPLICATIONS: {
    CREATE: '/restaurant-applications',
    MY: '/restaurant-applications/my',
    LIST: '/restaurant-applications',
    DETAIL: (id: string) => `/restaurant-applications/${id}`,
    APPROVE: (id: string) => `/restaurant-applications/${id}/approve`,
    REJECT: (id: string) => `/restaurant-applications/${id}/reject`,
  },
  RESTAURANTS: {
    LIST: '/restaurants',
    BY_SLUG: (slug: string) => `/restaurants/${slug}`,
  },
};
