export const API_ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    GOOGLE: '/auth/google',
    REGISTER: '/auth/register',
    CHECK_PHONE: '/auth/customer/check-phone',
    PHONE_OTP: '/auth/phone-login/otp',
    PHONE_VERIFY: '/auth/phone-login/verify',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    CHANGE_PASSWORD: '/auth/change-password',
    RESET_PASSWORD: '/auth/reset-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    CONFIRM_EMAIL: '/auth/confirm-email',
    RESEND_CONFIRMATION_EMAIL: '/auth/resend-confirmation-email',
    REFRESH_TOKEN: '/auth/refresh-token',
    TWO_FACTOR_SETUP: '/auth/2fa/setup',
    TWO_FACTOR_ENABLE: '/auth/2fa/enable',
    TWO_FACTOR_DISABLE: '/auth/2fa/disable',
    TWO_FACTOR_STATUS: '/auth/2fa/status',
    TWO_FACTOR_VALIDATE: '/auth/2fa/validate',
    TWO_FACTOR_REGENERATE_BACKUP_CODES: '/auth/2fa/regenerate-backup-codes',
    TWO_FACTOR_SETUP_NEW_DEVICE: '/auth/2fa/setup-new-device',
    TWO_FACTOR_CONFIRM_NEW_DEVICE: '/auth/2fa/confirm-new-device',
  },
  USERS: {
    ME: '/users/me',
    CHANGE_PASSWORD: '/users/change-password',
  },
  RESTAURANT_APPLICATIONS: {
    CREATE: '/restaurant-applications',
    MY: '/restaurant-applications/my',
    LIST: '/restaurant-applications',
    DETAIL: (id: string) => `/restaurant-applications/${id}`,
    APPROVE: (id: string) => `/restaurant-applications/${id}/approve`,
    REJECT: (id: string) => `/restaurant-applications/${id}/reject`,
  },
  CATEGORIES: {
    LIST: '/categories',
    CREATE: '/categories',
    DETAIL: (id: string) => `/categories/${id}`,
    UPDATE: (id: string) => `/categories/${id}`,
    DELETE: (id: string) => `/categories/${id}`,
  },
  DISHES: {
    LIST: '/dishes',
    CREATE: '/dishes',
    DETAIL: (id: string) => `/dishes/${id}`,
    UPDATE: (id: string) => `/dishes/${id}`,
    DELETE: (id: string) => `/dishes/${id}`,
  },
  RESTAURANTS: {
    LIST: '/restaurants',
    BY_SLUG: (slug: string) => `/restaurants/${slug}`,
  },
  RESERVATIONS: {
    LIST: '/reservations',
    CREATE: '/reservations',
    MY: '/reservations/my',
    CHECK_TABLES: '/reservations/check-tables',
    BY_CODE: (code: string) => `/reservations/code/${code}`,
    DETAIL: (id: string) => `/reservations/${id}`,
    UPDATE_STATUS: (id: string) => `/reservations/${id}/status`,
    CHECKIN: (code: string) => `/reservations/checkin/${code}`,
    CANCEL: (id: string) => `/reservations/${id}/cancel`,
    UPDATE: (id: string) => `/reservations/${id}`,
    STATS: '/reservations/stats',
    COMPLETE: (id: string) => `/reservations/${id}/complete`,
  },
  PAYMENTS: {
    LIST: '/payments',
    DETAIL: (id: string) => `/payments/${id}`,
    CASH: '/payments/cash',
    TRANSFER_INFO: '/payments/transfer-info',
    SEPAY_WEBHOOK: '/payments/sepay-webhook',
    POLL_PAYMENT: (paymentId: string) => `/payments/${paymentId}/status`,
  },
  FEEDBACKS: {
    LIST: '/feedbacks',
    DETAIL: (id: string) => `/feedbacks/${id}`,
    BY_ORDER: (orderId: string) => `/feedbacks/orders/${orderId}`,
    CREATE: (orderId: string) => `/feedbacks/orders/${orderId}`,
    UPDATE: (id: string) => `/feedbacks/${id}`,
    TOGGLE_PUBLISH: (id: string) => `/feedbacks/${id}/publish`,
    DELETE: (id: string) => `/feedbacks/${id}`,
  },
  EMPLOYEES: {
    LIST: '/employees',
    DETAIL: (id: string) => `/employees/${id}`,
    CREATE: '/employees',
    UPDATE: (id: string) => `/employees/${id}`,
    DELETE: (id: string) => `/employees/${id}`,
    RESET_PASSWORD: (id: string) => `/employees/${id}/reset-password`,
  },
};
